version: '1.0'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /Users/minwoo/Desktop/FA23/ds5760/final:/ds5760/mongo
    # environment: # disabling this for class practice only
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: examplepassword

